spring.application.name=demo
server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/student_employee?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=rom
spring.datasource.password=M@n!r0m123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Photo storage directory (relative to project root)
app.photo.upload-dir=uploads/photos
