name: CI Pipeline

on: [push]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Test
        run: |
          cd demo
          mvn clean package

      - name: Deploy on success
        if: success()
        run: |
          chmod +x deploy.sh
          ./deploy.sh

      - name: Notify failure
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_NAME }}
          password: ${{ secrets.MAIL_PASS }}
          subject: "FAILED: ${{ github.repository }} - Commit ${{ github.sha }}"
          to: ${{ github.event.head_commit.author.email || github.event.pusher.email || secrets.MAIL_TO }}
          cc: srengty@gmail.com
          from: ${{ secrets.MAIL_NAME }}
          body: |
            Job: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Author: ${{ github.event.head_commit.author.name }}
            Status: FAILED
            URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
